TARGET		= deductive_container_type

CXX		= g++
CXXFLAGS	= -std=c++14 -W -Wall

SRCS		= deductive_container_type.cpp

$(TARGET) :
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS)

clean :
	rm -f $(TARGET).o $(TARGET)
