CC = g++
CXXFLAGS = -std=c++11 -W -Wall

TARGET = select_optimized_function_at_compile_time
SRCS = select_optimized_function_at_compile_time.cc

target :
	$(CC) $(CXXFLAGS) $(SRCS) -o $(TARGET)

clean :
	rm -f $(TARGET)
